---
- name: add elastic gpg key
  apt_key:
    url: "{{ filebeat_gpg_url }}"

- name: add beats repository
  apt_repository:
    repo: "{{ filebeat_apt_repo_v6 }}"
    state: present
    update_cache: yes

- name: install filebeat
  apt:
    name: filebeat
    state: present
  notify:
    - restart filebeat

- name: Configure file beat to run automatically during startup
  shell: update-rc.d filebeat defaults 95 10
  become: true