---

- name: Upload filebeat_kafka service conf file
  template: src=filebeat_kafka.service.j2 dest=/lib/systemd/system/filebeat_kafka.service

- name: create kafka filebeat.yml
  template:
    src: filebeat_kafka.yml.j2
    dest: /etc/filebeat/filebeat_kafka.yml
  notify:
    - restart filebeat kafka
  tags:
    - update_filebeat_config

- name: flush handlers to prevent start then restart
  meta: flush_handlers
  tags:
    - update_filebeat_config

- name: start and enable filebeat
  service:
    name: filebeat_kafka
    state: started
    enabled: true
  tags:
    - update_filebeat_config

- name: Manually enable filebeat
  shell: systemctl enable filebeat_kafka.service
  tags:
    - update_filebeat_config