---
# It look up EC2 paramter store key, value credentials and other paramters that are set by terrform on EC2 level.

- name: paths to fetch from paramter store
  debug: msg="{{item}}"
  with_items:
    - "{{domain_path}}"
    - "{{environment_path}}"
    - "{{service_path}}"
  tags:
    - common_parameter_store

- name: lookup ssm parameter store for current app
  set_fact:
    ssm_domain_value: "{{ lookup('aws_ssm', ''~domain_path~'', 'region='~aws_region~'' ) }}"
    ssm_environment_value: "{{ lookup('aws_ssm', ''~environment_path~'', 'region='~aws_region~'' ) }}"
    ssm_service_value: "{{ lookup('aws_ssm', ''~service_path~'', 'region='~aws_region~'' ) }}"
  tags:
    - common_parameter_store