- src: geerlingguy.ruby
- src: knopki.locale
- src: git@gitlab.com:fynd/ansible-filebeat.git
  scm: git
  name: filebeat
  version: "v0.1.6"
- src: git@gitlab.com:fynd/ansible-metricbeat.git
  scm: git
  name: metricbeat
  version: "v0.1.2"
- src: git@gitlab.com:fynd/ansible-packetbeat.git
  scm: git
  name: packetbeat
- src: git@github.com:newrelic/infrastructure-agent-ansible.git
  scm: git
  name: newrelic-infrastructure-agent
- src: git@gitlab.com:fynd/ansible-prometheus-role.git
  scm: git
  name: prometheus
  version: "v0.1.3"