---
    # created with:
    # python -c 'import crypt; import os; print crypt.crypt("This is my Password", "$6$%s$" % (os.urandom(16).encode("base_64")[:8], ))'
- name: Create infra team users
  user: 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}" 
    append: yes
    shell: /bin/bash 
    comment: "{{ item.name }}"
    update_password: always
  with_items:
   - "{{ infra_team_users }}"
  tags:
   - infra_team_users
  no_log: true

- name: Place authorized_keys for infra team
  authorized_key: 
    user: "{{ item.name }}"
    key: "{{ lookup('file', '../files/ssh_key.'+ item.name + '.pub') }}"
  with_items:
   - "{{ infra_team_users }}"
  tags:
   - infra_team_users
  no_log: true

- name: Upload deploy SSH key
  copy: 
    src: 'files/ssh_key.deploy'
    dest: /home/deploy/.ssh/id_rsa 
    owner: deploy 
    group: deploy 
    mode: 0600 
    force: yes
  tags:
   - infra_team_users
  no_log: true

- name: Create regrowth team users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    append: yes
    shell: /bin/bash
    comment: "{{ item.name }}"
    update_password: always
  with_items:
   - "{{ regrowth_team_users }}"
  tags:
   - regrowth_team_users
   - reco_team_users
  no_log: true

- name: Place authorized_keys for regrowth team
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '../files/ssh_key.'+ item.name + '.pub') }}"
  with_items:
   - "{{ regrowth_team_users }}"
  tags:
   - regrowth_team_users
   - reco_team_users
  no_log: true

- name: Create vision team users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    append: yes
    shell: /bin/bash
    comment: "{{ item.name }}"
    update_password: always
  with_items:
   - "{{ vision_team_users }}"
  tags:
   - vision_team_users
  no_log: true

- name: Place authorized_keys for vision team
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '../files/ssh_key.'+ item.name + '.pub') }}"
  with_items:
   - "{{ vision_team_users }}"
  tags:
   - vision_team_users
  no_log: true

- name: Create orders team users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "{{ item.groups }}"
    append: yes
    shell: /bin/bash
    comment: "{{ item.name }}"
    update_password: always
  with_items:
   - "{{ orders_team_users }}"
  tags:
   - orders_team_users
  no_log: true

- name: Place authorized_keys for orders team
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '../files/ssh_key.'+ item.name + '.pub') }}"
  with_items:
   - "{{ orders_team_users}}"
  tags:
   - orders_team_users
  no_log: true

- name: Create common gateway users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    append: yes
    shell: /bin/bash
    comment: "{{ item.name }}"
    update_password: always
  with_items:
   - "{{ common_gateway_users }}"
  tags:
   - common_gateway_users
  no_log: true

- name: Place authorized_keys for common gateway team
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', '../files/ssh_key.'+ item.name + '.pub') }}"
  with_items:
   - "{{ common_gateway_users }}"
  tags:
   - common_gateway_users
  no_log: true

- name: Delete default users
  user: 
    name: "{{ item.name }}"
    state: present
  with_items:
   - "{{ default_users }}"
  ignore_errors: true

- name: Copy deploy codecommit private key
  copy: content="{{ code_commit_private_key }}" dest=/home/{{deploy_user_name }}/.ssh/code_commit force=yes mode=0600
  become: true
  become_user: "{{ deploy_user_name }}"

- name: create ssh config file
  template: src=ssh/ssh_config.j2 dest=/home/{{deploy_user_name }}/.ssh/config mode=0600
  become: true
  become_user: "{{ deploy_user_name }}"

