---
newrelic_license_key: 79c6aa01016a9d49f2f17196aebeb8e490dd654b
logzio_token: ZzbAegtLHgiZspMVoQhgsZHFqGyFhzhn
ssm_env: production
aws_region: ap-south-1
kafka_brokers: ["10.0.12.137:9092", "10.0.12.138:9092", "10.0.140.139:9092"]
filebeat_kafka_enabled: true