- name: get system memory
  set_fact: 
    system_memory: "{{ system_memory_GB|float * 950 }}" #{{ ansible_memory_mb.real.total }}"
  when: auto_calculate_ulimits

- name: calculate file-max from system memory
  set_fact:
    file_max: "{{ system_memory|int * 100 }}"
  when: auto_calculate_ulimits

- name: set user ulimit
  set_fact:
    ulimit: "{{ 1048576 if file_max|int > 1048576 else file_max|int }}"
  when: auto_calculate_ulimits

# - name: calculate open files ulimit from system file-max
#   set_fact:
#     ulimit_open_files: "{{ file_max|int / 10 }}"

- name: print file_max
  debug:
    msg: "file max is {{ file_max }}"

- name: print ulimit
  debug:
    msg: "ulimit is {{ ulimit }}"

- name: change comment /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^# Ansible changes."
    line="# Ansible changes."

- name: change soft nofile /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* soft nofile"
    line="* soft nofile {{ ulimit }}"

- name: change hard nofile /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* hard nofile"
    line="* hard nofile {{ ulimit }}"

- name: change soft nproc /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* soft nproc"
    line="* soft nproc {{ ulimit }}"

- name: change hard nproc /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^\* hard nproc"
    line="* hard nproc {{ ulimit }}"

# root open file limit
- name: change root soft nofile /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^root soft nofile"
    line="root soft nofile {{ ulimit }}"

- name: change root hard nofile /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^root hard nofile"
    line="root hard nofile {{ ulimit }}"

- name: change root soft nproc /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^root soft nproc"
    line="root soft nproc {{ ulimit }}"

- name: change root hard nproc /etc/security/limits.conf
  lineinfile:
    dest=/etc/security/limits.conf
    regexp="^root hard nproc"
    line="root hard nproc {{ ulimit }}"

- name: Set sysctl File Limits
  template:
    src: 50-fs.conf.j2
    dest: /etc/sysctl.d/50-fs.conf

- name: Set Shell File Limits
  template:
    src: 91-nofiles.conf.j2
    dest: /etc/security/limits.d/91-nofiles.conf

- name: change file-max in /etc/sysctl.conf
  lineinfile:
    dest=/etc/sysctl.conf
    regexp="^fs.file-max="
    line="fs.file-max= {{ file_max }}"

- name: apply change to file-max in /etc/sysctl.conf
  shell: sysctl -p

- name: change default user level limits
  lineinfile:
    dest=/etc/systemd/system.conf
    regexp="^#DefaultLimitNOFILE="
    line="DefaultLimitNOFILE= {{ ulimit }}"

- name: change root hard nofile /etc/security/limits.conf
  lineinfile:
    dest=/etc/systemd/user.conf
    regexp="^#DefaultLimitNOFILE="
    line="DefaultLimitNOFILE= {{ ulimit }}"
