---
# This playbook contains common plays that will be run on all nodes.

  - name: Update apt cache
    apt: update_cache=yes cache_valid_time=86400
    tags:
      - setup

  - name: Install required system packages
    apt: pkg={{ item }} state=present
    with_items: "{{ base_packages }}"
    tags:
      - setup
      - packages

  - include: install_amazon_ssm_agent.yml
    tags:
      - packages

  - include: create_swap_file.yml
    when: create_swap_file
    tags:
      - swap

  - include: create_directory_structure.yml
    tags:
      - base_dirs

  - include: configure_tz.yml
    tags:
      - setup
      - timezone

  - include: update_hostname.yml
    tags:
      - setup
      - hostname

  - include: setup_ntp.yml
    tags:
      - setup

  - include: configure_sshd.yml
    tags:
      - setup
      - ssh

  - include: increase_ulimit.yml
    tags:
      - setup
      - ulimit

  - include: disable_auto_update.yml
    tags:
      - setup
      - disable_update