- name: Get current hostname
  shell: cat /etc/hostname
  register: current_hostname

- name: Get local ipv4 address
  shell: curl {{ ec2_instance_metadata_url }}/local-ipv4
  register: local_ipv4_address

- name: Set value of variable for assigning new hostname
  set_fact:
    new_hostname="{{ hostname.format(local_ipv4_address.stdout.split('.')[2],
    local_ipv4_address.stdout.split('.')[3]) }}"


- name: Set the new hostname
  shell: hostname {{ new_hostname }}

- name: remove older /etc/hostname file
  file: path=/etc/hostname state=absent

- name: update /etc/hostname file
  template: src=hostname.j2 dest=/etc/hostname mode=0644

- name: update hostname in /etc/hosts file
  lineinfile:
    dest=/etc/hosts
    regexp='^'
    line='127.0.1.1 {{ new_hostname }}'
    state=present