---
# The version of metricbeat to install
metricbeat_version: 6.1

# The contents of this variable will be placed into the `metricbeat_ca_path`
# This should either be set to a string containing your CA certificate or
# use a lookup plugin to retrieve it.
#  ex:
#   metricbeat_ca_cert: "{{ lookup('file', '/path/to/ca.crt') }}"
metricbeat_ca_cert: null
# Path to which the above certificate will be uploaded
metricbeat_ca_path: /etc/metricbeat/ca.crt

# `metricbeat_config` is templated directly into metricbeat.yml for the config.
# You are expected to override this variable, as these configurations are
# only suited for development purposes.
# See https://github.com/elastic/metricbeat/blob/master/etc/metricbeat.yml for
# an exhaustive list of configurations.
metricbeat_config:
  fields:
    logzio_codec: json
    token: "{{logzio_token}}"
    type: ec2
    environment: "{{ env | default('dev')}}"
  fields_under_root: true
  metricbeat.modules:
    - module: system
      metricsets:
        - cpu
        - load
        - core
        - diskio
        - filesystem
        - fsstat
        - memory
        - network
        - process
        - socket
      enabled: false
      period: 60s
      processes: ['.*']
    - module: nginx
      metricsets: ["stubstatus"]
      enabled: false
      period: 60s
      hosts: ["http://127.0.0.1"]
    - module: redis
      metricsets: ["info", "keyspace"]
      enabled: false
      period: 60s
      hosts: ["127.0.0.1:6379"]
      timeout: 1s
      network: tcp
      maxconn: 1
  output:
    logstash:
      hosts: ["{{logstash_proxy_url}}"]

#  The below configuration is used for Filebeat 5.0 or higher
      ssl:
        certificate_authorities: ["{{ filebeat_ca_path }}"]
#================================ Logging ======================================
  logging.level: error
  logging.metrics.enabled: true
  logging.metrics.period: 30s
  logging.to_files: true
  logging.files:
    path: /var/log/metricbeat
    name: metricbeat.log
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 50
    permissions: 0600
  logging.json: true

# Repository settings
metricbeat_gpg_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
## Debian
metricbeat_apt_repo_v1: "deb https://packages.elastic.co/beats/apt stable main"
metricbeat_apt_repo_v5: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
metricbeat_apt_repo_v6: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
metricbeat_apt_repo: "{{ metricbeat_version|version_compare('5', '>')|ternary(metricbeat_apt_repo_v5, metricbeat_apt_repo_v6) }}"
## Redhat
metricbeat_repo_url_v1: https://packages.elastic.co/beats/yum/el/$basearch
metricbeat_repo_url_v5: https://artifacts.elastic.co/packages/5.x/yum
metricbeat_repo_url: "{{ metricbeat_version|version_compare('5', '>')|ternary(metricbeat_repo_url_v1, metricbeat_repo_url_v5) }}"