---
# The version of packetbeat to install
packetbeat_version: 5.3

# `packetbeat_config` is templated directly into packetbeat.yml for the config.
# You are expected to override this variable, as these configurations are
# only suited for development purposes.
# See https://github.com/elastic/packetbeat/blob/master/etc/packetbeat.yml for
# an exhaustive list of configurations.
packetbeat_config:
  fields:
    env: "{{ env | default('dev')}}"
  packetbeat.interfaces.device: any
  packetbeat.flows:
    enabled: false
    timeout: 30s
    period: 60s
  packetbeat.protocols.icmp:
    enabled: false
  packetbeat.protocols.mongodb:
    enabled: true
    ports: [27017]
    max_docs: 10
    max_doc_length: 5000
    transaction_timeout: 10s
    send_request: true
    send_response: true
  processors:
    - drop_event:
        when:
           equals:
               mongodb.fullCollectionNAme: admin.$cmd
  output:
     elasticsearch:
      hosts: ["{{ elasticsearch_proxy_url }}"]
      username: "{{ es_filebeat_user }}"
      password: "{{ es_filebeat_password }}"
      index: "packetbeat-{{ env }}-%{+YYYY.MM.dd}"
  logging:
    to_syslog: false
    to_files: true
    level: debug
    files:
      - path: /var/log/packetbeat
      - name: packetbeat.log
      - keepfiles: 5

# The contents of this variable will be placed into the `packetbeat_ca_path`
# This should either be set to a string containing your CA certificate or
# use a lookup plugin to retrieve it.
#  ex:
#   packetbeat_ca_cert: "{{ lookup('file', '/path/to/ca.crt') }}"
packetbeat_ca_cert: null
# Path to which the above certificate will be uploaded
packetbeat_ca_path: /etc/packetbeat/ca.crt

# Repository settings
packetbeat_gpg_url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
## Debian
packetbeat_apt_repo_v1: "deb https://packages.elastic.co/beats/apt stable main"
packetbeat_apt_repo_v5: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
packetbeat_apt_repo: "{{ packetbeat_version|version_compare('5', '<')|ternary(packetbeat_apt_repo_v1, packetbeat_apt_repo_v5) }}"
## Redhat
packetbeat_repo_url_v1: https://packages.elastic.co/beats/yum/el/$basearch
packetbeat_repo_url_v5: https://artifacts.elastic.co/packages/5.x/yum
packetbeat_repo_url: "{{ packetbeat_version|version_compare('5', '<')|ternary(packetbeat_repo_url_v1, packetbeat_repo_url_v5) }}"